spring:
  application:
    name: zuul-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10KB
      file-size-threshold: 5
      max-request-size: 1MB

server:
  port: 5001

zuul:
  routes:
    order:
      path: /order/**
      serviceId: order-service
    user:
      path: /user/**
      serviceId: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
