spring:
  application:
    name: retry-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

client:
  request:
    connection-request-timeout: 1000
    connect-timeout: 1000
    read-timeout: 1500

eureka-provider:
  ribbon:
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 1

