spring:
  application:
    name: user-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5
      max-file-size: 50KB
      max-request-size: 1MB
server:
  port: 7200
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

