spring:
  application:
    name: eureka-client
server:
  port: 7200
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

