spring:
  application:
    name: hystrix-turbine
turbine:
  clusterNameExpression: "'default'"
  app-config: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 3001
